name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  # -----------------------------
  # 1. TEST STAGE
  # -----------------------------
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Syntax Check
      run: python -m py_compile app.py

  # -----------------------------
  # 2. BUILD & PUSH STAGE
  # -----------------------------
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t avanis55/insurance-app:latest .

    - name: Push Docker Image
      run: docker push avanis55/insurance-app:latest

  # -----------------------------
  # 3. DEPLOY STAGE
  # -----------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2 Minikube
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          # Ensure Minikube is running
          if ! minikube status | grep -q "Running"; then
            minikube start --driver=docker
          fi

          # Update Secret
          kubectl delete secret groq-secret --ignore-not-found
          kubectl create secret generic groq-secret \
            --from-literal=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}

          # Apply manifests (important!)
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          # Force new image pull
          kubectl rollout restart deployment/insurance-app

          # Wait for rollout
          kubectl rollout status deployment/insurance-app --timeout=180s
          
          # Debug info
          kubectl get pods
          kubectl get services